apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
 name: cluster-admin-binding
subjects:
- kind: User
  name: system:serviceaccount:{YOURNAMESPACE}:default
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""